version: "3.9"

services:
  website:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: astro_website
    ports:
      - "80:4321"
    restart: unless-stopped
    volumes:
      - ./mount/webdav_data/data:/app/content/blog
      - ./mount/webdav_data/data/images:/app/dist/client/images

  webdav:
    image: bytemark/webdav
    container_name: webdav_server
    environment:
      AUTH_TYPE: Basic
      USERNAME: "jakob"
      PASSWORD: "secret"
      # DIRECTORY defaults to /var/lib/dav; can mount your own below
    volumes:
      - ./mount/webdav_data:/var/lib/dav
    ports:
      - "8081:80"
    restart: unless-stopped
